trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(BuildID)
    - bash: echo $(SourceBranchName)
    - bash: echo $(SourceDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: java -version
    - bash: maven -version
    - bash: node --version
    - bash: python --version
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
#   - job: SecondJob
#     steps:
#     - bash: echo Build SecondJob
# - stage: DevDeploy
#   variables:
#     environment: Dev
#   dependsOn: Build
#   jobs:
#   - job: DevDeployJob
#     steps:
#     - bash: echo DevDeployJob
# - stage: testDeploy
#   variables:
#     environment: test
#   dependsOn: Build
#   jobs:
#   - job: testDeployJob
#     steps:
#     - bash: echo testDeployJob
# - stage: prodDeploy
#   variables:
#     environment: prod
#   dependsOn:
#   - DevDeploy
#   - testDeploy
#   jobs:
#   - job: prodDeployJob
#     steps:
#     - bash: echo prodDeployJob