trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
  - job: firstjob
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script first'
- stage: dev
  dependsOn: build
  jobs:
  - job: devdeployjob
    steps:
    - script: echo devdeploy!
      displayName: 'Run a one-line script first'
- stage: QA
  dependsOn: dev
  jobs:
  - job: QAdeployjob
    steps:
    - script: echo QAdeploy!
      displayName: 'Run a one-line script first'
- stage: prod
  dependsOn: QA
  jobs:
  - job: proddeployjob
    steps:
    - script: echo proddeploy!
      displayName: 'Run a one-line script first'


