trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: builddeploy
  variables:
    environment : build
    jobs:
    - job: firstjob
      steps:
      - script: echo $(environment)builddeploy!
- stage: devdeploy
  variables:
    environment : dev
  dependsOn: build
  jobs:
  - job: devdeployjob
    steps:
    - script: echo $(environment)devdeploy!
      displayName: 'Run a one-line script first'
- stage: QAdeploy
  variables:
    environment : QA
  dependsOn: dev
  jobs:
  - job: QAdeployjob
    steps:
    - script: echo $(environment)QAdeploy!
      displayName: 'Run a one-line script first'
- stage: proddeploy
  variables:
    environment : prod
  dependsOn: QA
  jobs:
  - job: proddeployjob
    steps:
    - script: echo $(environment)proddeploy!
      displayName: 'Run a one-line script first'


