trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  variables:
    environment : build
    jobs:
    - job: firstjob
      steps:
      - script: echo $(environment)build!
- stage: dev
  variables:
    environment : dev
  dependsOn: build
  jobs:
  - job: devdeployjob
    steps:
    - script: echo $(environment)dev!
      displayName: 'Run a one-line script first'
- stage: QA
  variables:
    environment : QA
  dependsOn: dev
  jobs:
  - job: QAdeployjob
    steps:
    - script: echo $(environment)QA!
      displayName: 'Run a one-line script first'
- stage: prod
  variables:
    environment : prod
  dependsOn: QA
  jobs:
  - job: proddeployjob
    steps:
    - script: echo $(environment)prod!
      displayName: 'Run a one-line script first'


