trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: firstjob
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script first'
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
- job: secondjob
  dependsOn: firstjob
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script second'
- job: thirdjob
  dependsOn: firstjob
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script third'

