trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: devdeploy
  variables:
    environment : dev
  jobs:
  - job: devdeployjob
    steps:
    - script: echo $(environment)deploy!
      displayName: 'Run a one-line script first'
- stage: QAdeploy
  variables:
    environment : QA
  dependsOn: devdeploy
  jobs:
  - job: QAdeployjob
    steps:
    - script: echo $(environment)deploy!
      displayName: 'Run a one-line script first'
- stage: proddeploy
  variables:
    environment : prod
  dependsOn: QAdeploy
  jobs:
  - job: proddeployjob
    steps:
    - script: echo $(environment)deploy!
      displayName: 'Run a one-line script first'


