# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: job1
  steps:
  - script: echo Hello, world for job1!
    displayName: 'Run a one-line script'
- job: job2
  steps:
  - script: echo Hello, world for job2!
    displayName: 'Run a one-line script'


